name: akk_pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - sra-tools=3.1.1
  - kneaddata=0.10.0
  - metaphlan=4.0
  - panphlan=3.1
  - samtools=1.16
  - diamond=2.1.8
  - bowtie2=2.5.1
  - prokka=1.14.6
  - mmseqs2=14.7e284
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - r-base=4.2
  - r-vegan
  - r-ggplot2
  - r-ape
  - r-dendextend   
